# Generated by Django 5.0.4 on 2024-06-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='government',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='government',
            name='Government_obj',
        ),
        migrations.RemoveField(
            model_name='government',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='DateTime',
        ),
        migrations.AlterField(
            model_name='region',
            name='LogoLink',
            field=models.CharField(blank=True, default='/static/img/default_region.jpg', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='Wikipedia',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='menuItems',
            field=models.CharField(blank=True, default='[]', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='modelType',
            field=models.CharField(blank=True, default='provState', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='nameType',
            field=models.CharField(default='State', max_length=100),
        ),
    ]
