# Generated by Django 5.0.4 on 2024-06-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('chain_length', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='[]', null=True)),
                ('data_added_datetime', models.DateTimeField(blank=True, null=True)),
                ('genesisType', models.CharField(default='0', max_length=50)),
                ('genesisId', models.CharField(db_index=True, default='0', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(default='0', max_length=50)),
                ('self_declare_active', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
                ('deactivated_time', models.DateTimeField(blank=True, null=True)),
                ('supported_chains', models.TextField(blank=True, default='[]', null=True)),
                ('publicKey', models.CharField(default='0', max_length=200)),
                ('signature', models.CharField(default='0', max_length=200)),
                ('User_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DataPacket',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('data', models.TextField(blank=True, default='[]', null=True)),
                ('chainId', models.CharField(default='0', max_length=50)),
                ('publicKey', models.CharField(default='0', max_length=200)),
                ('signature', models.CharField(default='0', max_length=200)),
                ('Node_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('blockchainId', models.CharField(default='0', max_length=50)),
                ('publicKey', models.CharField(default='0', max_length=200)),
                ('signature', models.CharField(default='0', max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('index', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(default='0', max_length=100)),
                ('previous_hash', models.CharField(default='0', max_length=100)),
                ('reward', models.CharField(default='0', max_length=1000000)),
                ('data', models.TextField(blank=True, default='[]', null=True)),
                ('number_of_peers', models.IntegerField(default=1)),
                ('is_valid', models.BooleanField(default=False)),
                ('script', models.TextField(blank=True, null=True)),
                ('Node_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeUpdate',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('pointerId', models.CharField(default='0', max_length=50)),
                ('ai_capable', models.BooleanField(default=False)),
                ('accessed', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('fail_time', models.DateTimeField(blank=True, null=True)),
                ('deactivated_time', models.DateTimeField(blank=True, null=True)),
                ('strike_id', models.CharField(default='0', max_length=50)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('publicKey', models.CharField(default='0', max_length=200)),
                ('signature', models.CharField(default='0', max_length=200)),
                ('CreatorNode_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_node_obj', to='blockchain.node')),
                ('TargetNode_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_node_obj', to='blockchain.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('publicKey', models.CharField(default='0', max_length=200)),
                ('signature', models.CharField(default='0', max_length=200)),
                ('pointerId', models.CharField(db_index=True, default='0', max_length=50)),
                ('pointerType', models.CharField(default='0', max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('Node_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.node')),
            ],
        ),
    ]
