# Generated by Django 5.0.4 on 2024-06-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_remove_block_automated_remove_block_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ai_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='fcm_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
