# Generated by Django 5.0.4 on 2024-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_node_ai_capable_node_fcm_capable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='required_validators',
            field=models.IntegerField(default=1),
        ),
    ]
