# Generated by Django 5.0.4 on 2024-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_block_required_validators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='block',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='datapacket',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeupdate',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
