# Generated by Django 5.0.4 on 2024-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sonet_logolink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonet',
            old_name='subtitle',
            new_name='Subtitle',
        ),
        migrations.RenameField(
            model_name='sonet',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='savepost',
            name='pointerId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uservote',
            name='pointerId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
