# Generated by Django 5.0.4 on 2024-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_subtitle_sonet_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='savepost',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sonet',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userpubkey',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='uservote',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_on_node',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
